@server=http://localhost:4004
@username=alice
@password=


### CustomerMaster
# @name CustomerMaster_GET
GET {{server}}/odata/v4/learningervice/CustomerMaster
Authorization: Basic {{username}}:{{password}}


### CustomerMaster
# @name CustomerMaster_POST
POST {{server}}/odata/v4/learningervice/CustomerMaster
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "CustomerCode": "00001",
  "FirstName": "Afshan",
  "LastName": "Ansari",
  "EmailAddress": "afgshanansari144@gmail.com",
  "MobileNo": "8273260999"
}


### CustomerMaster
# @name CustomerMaster_PATCH
PATCH {{server}}/odata/v4/learningervice/CustomerMaster/14760964-4f29-4948-867f-862c04904fd4
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "CustomerGuid": "14760964-4f29-4948-867f-862c04904fd4",
  "CustomerCode": "CustomerCode-14760964",
  "FirstName": "FirstName-14760964",
  "LastName": "LastName-14760964",
  "EmailAddress": "EmailAddress-14760964",
  "MobileNo": "MobileNo-14760964",
  "createdAt": "2012-05-03T00:00:00.000Z",
  "createdBy": "createdBy.8sdms@example.com",
  "modifiedAt": "2013-07-04T00:00:00.000Z",
  "modifiedBy": "modifiedBy.8sdms@example.org"
}


### CustomerMaster
# @name CustomerMaster_DELETE
DELETE {{server}}/odata/v4/learningervice/CustomerMaster/14760964-4f29-4948-867f-862c04904fd4
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
